chore(github-actions): comment out Cloudflare cache purge workflow

diff --git a/.github/workflows/cloudflare.yml b/.github/workflows/cloudflare.yml
--- a/.github/workflows/cloudflare.yml
+++ b/.github/workflows/cloudflare.yml
@@ -1,28 +1,28 @@
-name: Purge Cloudflare Cache
-
-on:
-  push:
-    branches:
-      - main
-      - theme-only
-  workflow_dispatch:
-
-jobs:
-  purge-cache:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Purge Cloudflare Cache
-        env:
-          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
-          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
-               -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
-               -H "Content-Type: application/json" \
-               --data '{"purge_everything":true}')
-          if [ $response -ne 200 ]; then
-            echo "Failed to purge Cloudflare cache. HTTP status code: $response"
-            exit 1
-          else
-            echo "Successfully purged Cloudflare cache."
-          fi
+# name: Purge Cloudflare Cache
+#
+# on:
+#   push:
+#     branches:
+#       - main
+#       - theme-only
+#   workflow_dispatch:
+#
+# jobs:
+#   purge-cache:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Purge Cloudflare Cache
+#         env:
+#           CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
+#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+#         run: |
+#           response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
+#                -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
+#                -H "Content-Type: application/json" \
+#                --data '{"purge_everything":true}')
+#           if [ $response -ne 200 ]; then
+#             echo "Failed to purge Cloudflare cache. HTTP status code: $response"
+#             exit 1
+#           else
+#             echo "Successfully purged Cloudflare cache."
+#           fi
